# Generated by Django 5.0.6 on 2024-06-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcategory',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='bg_color',
        ),
    ]
