# Generated by Django 5.0.6 on 2024-06-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_name', models.CharField(max_length=50, unique=True)),
                ('icon_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Назва та іконка зміни в рахунку',
                'verbose_name_plural': 'Назви та іконки змін в рахунках',
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'account_name')},
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.changetype')),
            ],
            options={
                'verbose_name': 'Зміна в рахунку',
                'verbose_name_plural': 'Зміни в рахунках',
            },
        ),
    ]
