# Generated by Django 5.0.6 on 2024-06-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_options_accounthistory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthistory',
            name='account_name',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='account',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
            preserve_default=False,
        ),
    ]
