# Generated by Django 5.0.6 on 2024-06-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_account_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
