# Generated by Django 5.0.6 on 2024-06-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_password',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
